# Generated by Django 5.0.1 on 2024-06-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_simulador', '0002_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
